name: svg_to_path_generator
description: Svg to path generator
version: 1.0.0+1
homepage: https://github.com/gcoderbh/svg_to_path_generator/tree/master/packages/svg_to_path_generator

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  build: ^2.0.2
  source_gen: ^1.0.1
  xml2json: ^5.2.0
  xml: ^6.2.2
  path_parsing: ^1.0.1
  analyzer: ^5.10.0
  svg_to_path_annotation: ^1.0.0

dev_dependencies:
  build_runner: ^2.3.3